"""
Hybrid decoding: base model generates reasoning, fine-tuned adapter generates the answer.

Requires vLLM. The LLM must be loaded with enable_lora=True so the adapter
can be toggled between the two generation phases without reloading the model.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol

from thinkpack.parse import _GenerationOutput, parse


class _LLM(Protocol):
    """Minimal protocol for a vLLM-compatible LLM instance."""

    def generate(
        self,
        prompts: list[str],
        sampling_params: Any,
        lora_request: Any = None,
    ) -> Sequence[_GenerationOutput]: ...


@dataclass
class HybridResult:
    """Output from a single hybrid decoding generation.

    Contains the reasoning produced by the base model, the answer produced
    by the fine-tuned model, and a combined raw string for convenience.
    """

    # reasoning block content, generated by the base model
    reasoning: str
    # answer text, generated by the fine-tuned model
    answer: str
    # full combined string reconstructed as "<tag>reasoning</tag>\nanswer"
    raw: str


def _build_reasoning_prefix(reasoning: str, tag: str) -> str:
    """Wrap a reasoning string in its original tag to form a closed block.

    Used to construct the phase 2 prompt prefix so the fine-tuned model
    receives the full reasoning block before generating its answer.

    Returns a string of the form "<tag>\\nreasoning\\n</tag>\\n".
    """
    return f"<{tag}>\n{reasoning}\n</{tag}>\n"


def hybrid_generate(
    prompts: list[str],
    llm: _LLM,
    lora_request: Any,
    sampling_params: Any,
    prefixed: bool = False,
) -> list[HybridResult]:
    """Run hybrid decoding: base model reasons, fine-tuned model answers.

    Two sequential generation passes over the same loaded vLLM model:

    Phase 1 — reasoning (no adapter):
        Generates with lora_request=None so the base model produces a
        reasoning block freely, without fine-tuning influence.

    Phase 2 — answer (with adapter):
        Prepends the reasoning block from phase 1 to each prompt, then
        generates with the provided lora_request so the fine-tuned model
        produces the final answer conditioned on that reasoning.

    The LLM must be loaded with enable_lora=True to support toggling the
    adapter between phases. Pass the same SamplingParams to both phases;
    for different per-phase params, use steer() and parse() directly.

    Set prefixed=True for PREFIXED template models (e.g. OLMo-3) whose
    generation prompt already ends with the opening reasoning tag — used
    when parsing the phase 1 outputs.

    Returns a list of HybridResult, one per prompt.
    """
    # phase 1: base model generates reasoning (no adapter)
    phase1_outputs = llm.generate(
        prompts=prompts,
        sampling_params=sampling_params,
        lora_request=None,
    )

    # parse reasoning from each phase 1 output (first sample only)
    phase1_parsed = [
        parse(
            response=output.outputs[0].text,
            prefixed=prefixed,
        )
        for output in phase1_outputs
    ]

    # build phase 2 prompts: original prompt + closed reasoning block
    # use the detected tag from phase 1, falling back to "think" if not found
    phase2_prompts = []
    for prompt, p1 in zip(prompts, phase1_parsed):
        if p1.has_valid_reasoning:
            tag = p1.reasoning_tag or "think"
            prefix = _build_reasoning_prefix(reasoning=p1.reasoning, tag=tag)
            phase2_prompts.append(prompt + prefix)
        else:
            # no usable reasoning — phase 2 proceeds without a prefix
            phase2_prompts.append(prompt)

    # phase 2: fine-tuned model generates answer (with adapter)
    phase2_outputs = llm.generate(
        prompts=phase2_prompts,
        sampling_params=sampling_params,
        lora_request=lora_request,
    )

    # combine reasoning and answer into HybridResult objects
    results = []
    for p1, output in zip(phase1_parsed, phase2_outputs):
        answer = output.outputs[0].text.strip()
        tag = p1.reasoning_tag or "think"
        raw = (
            _build_reasoning_prefix(reasoning=p1.reasoning, tag=tag) + answer
            if p1.has_valid_reasoning
            else answer
        )
        results.append(
            HybridResult(
                reasoning=p1.reasoning,
                answer=answer,
                raw=raw,
            )
        )

    return results
